config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope "(:locale)", locale: /en|de/ do
    root "courses#index"
    post 'courses/:id/enroll', to: "courses#enroll"
    # get "courses/:id", to: "courses#show"

    post 'sessions/create'
    get 'login', to: "sessions#new"
    # get 'users/new'
    resources :users

    delete 'sessions/logout', to: "sessions#destroy"

    post "courses/search", to: "courses#search"
    get "courses/auto_complete", to: "courses#auto_complete"

    get "dashboard", to: "courses#dashboard"
    get "/courses/:id", to: "courses#show", as: :my_course
    get "courses/:course_id/lessons/:id", to: "lessons#show", as: :lesson
    get "courses/:id/detail", to: "courses#detail"

  end

  namespace :admin do
    root to: "courses#index"
    get 'courses', to: "courses#index"

    patch "courses/approve", to: "courses#approve", as: :approve_course

    resources :courses
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  ON_GOING_STATUS = 0
  COMING_STATUS = 1
  PASSED_STATUS = 2

  searchkick searchable: [:name]

  has_many :course_students
  has_many :students, -> { where(role: 'student') }, class_name: 'User', through: :course_students

  has_many :lessons

  mount_uploader :image, ImageUploader

  validates :name, length: { in: 5..30 }

  def total_request
    CourseStudent.where(course_id: id, status: 'pending').count
  end
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :course
  belongs_to :student, class_name: 'User', foreign_key: :student_id

  enum status: [:pending, :approved]

  validates :course_id, uniqueness: { scope: :student_id }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :name, presence: true,
            uniqueness: { scope: :course_id,
                          message: 'cannot have two lessons with same name in a course' }

  validates :document_url, presence: true
                        #  & validate format theo dinh dang url = regular expression

  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password

  enum role: [ :student, :admin ]

  before_save :encrypt_password
  after_save :clear_password

  has_many :course_students, foreign_key: :student_id
  has_many :courses, through: :course_students

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  # validates :password, confirmation: true

  def encrypt_password
  	if password.present?
  		self.salt = BCrypt::Engine.generate_salt
  		self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
  	end
  end

  def clear_password
  	self.password = nil
  end

  def self.authenticate(username_or_email = "", login_password = "")
    return unless username_or_email || login_password
    user = User.where(email: username_or_email).first
    user = User.where(username: username_or_email).first unless user

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :authenticate_user

  # Some code here
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @pending_requests = CourseStudent.where(course_id: params[:id], status: 'pending')
  end

  def approve
    CourseStudent.find(params[:request_id]).update(status: 'approved')
  end

  def new
    @course = Course.new
  end


  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "Course is created successful"
      redirect_to admin_courses_path
    else
      flash.now[:error] = @course.errors.full_messages
      render 'new'
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :image, :description)
  end

end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
  before_action :authenticate_user

  # Some code here
  def index
    @lessons = Lesson.includes(:course).all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to admin_lessons_path
    else
      render 'new'#, flash: {error: 'Error'}
    end

  end

  private
  def lesson_params
    params.require(:lesson).permit(:name, :document_url, :video_url, :description, :course_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def default_url_options
    { locale: I18n.locale }
  end

  protected # can be access inside this and other children class

  def set_locale
    I18n.locale = params[:locale] if params[:locale]
  end

  def authenticate_user
    user_logged_in = false
    if session[:current_user_id]
      user_logged_in = User.where(id: session[:current_user_id]).exists? ? true : false
    end

    if user_logged_in
      @current_user = User.find(session[:current_user_id])
      return true
    else
      return redirect_to new_user_path(locale: I18n.locale)
    end
  end

  # check if user logged in or not.
  # if yes, prevent he from login and sign up page
  def login_user
    if session[:current_user_id]
      return redirect_to root_path(locale: I18n.locale)
    else
      return true
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user, except: [:index, :auto_complete, :search]
	def index
		if session[:current_user_id]
			@current_user = User.where(id: session[:current_user_id]).first
		end

		@enrolled_courses = @current_user ? @current_user.courses : []
		enrolled_course_ids = @enrolled_courses.size > 0 ? @enrolled_courses.select(:id) : []
		@courses = Course.where.not(id: enrolled_course_ids)
	end

  def dashboard

		@enrolled_courses = @current_user.courses.where(
														course_students: { status: 'approved' }
												)

	end

  def enroll
		@course = Course.find(params[:id])

		if @current_user.courses.include? @course
			respond_to do |format|
				format.json { render json: {}, status: 400 }
				format.js
			end
		else
			@current_user.courses << @course
			respond_to do |format|
				format.json { render :json => {course: @course}, status: :ok }
				format.js
			end
		end
	end

  def search
		@courses = Course.search(params[:query])
		render :index
	end

  def show
		@course = Course.find(params[:id])
		@lessons = @course.lessons

	end

  def auto_complete
		render json: Course.search(params[:query], limit: 10).map(&:name)
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user

  def show
    @course = Course.find(params[:course_id])
    @lesson = Lesson.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :login_user, only: [:new, :create]

  def new
  end

  def create
  	authorized_user = User.authenticate(params[:username_or_email], params[:password])

    if authorized_user
      session[:current_user_id] = authorized_user.id

      flash[:notice] = "Welcome to the LMS"
      redirect_to root_path
    else
      flash[:notice] = "Invalid Username or Password"
      render :new
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_user, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You register successfully"
      redirect_to :root
    else
      flash[:notice] = "Something went wrong with your registration"
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/courses/_form.html.erb
<div class="col-md-offset-3" style="margin-top: 50px">
  <h2> New course </h2>

  <%= form_for [:admin, @course] do |f| %>

      <% if flash[:error] %>
        <div class="text-danger">
          <% flash[:error].each do |msg| %>
            <p> <%= msg %> </p>
          <% end %>
        </div>
      <% end %>

      <div class="row col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Create', class: 'btn btn-primary pull-right' %>
        </div>
      </div>

  <% end %>
</div>

app/views/admin/courses/index.html.erb
<div class="container">
  <% if flash[:notice] %>
      <div class="text-success">
        <%= flash[:notice] %>
      </div>
  <% end %>

  <h2>
    <div class="pull-left">Courses</div>
    <div class="pull-right">
      <%= link_to 'New Course', new_admin_course_path %>
    </div>
  </h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Image</th>
        <th>Total Requests</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.name %></td>
          <td>
            <%= image_tag course.image.thumb.url  %>
          </td>
          <td>
            <%= course.total_request %>
          </td>

          <td><%= course.description %></td>
          <td>
            <%= link_to "View", admin_course_path(course.id) %>
            <%= link_to "Edit", "#" %>
            <%= link_to "Delete", "#" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/courses/new.html.erb
<%= render 'form' %>

app/views/admin/courses/show.html.erb
<div class="container">
  <h2><%= @course.name %></h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @pending_requests.each do |request| %>
          <tr id="approve-btn-<%= request.id %>" >
            <td><%= request.student.username %></td>
            <td>
              <a class="request-approve" data-id="<%= request.id %>">Approve</a>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/lessons/_form.html.erb
<div class="col-md-offset-3">
  <%= form_for [:admin, @lesson] do |f| %>
      <div class="row col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :course %>
          <%= f.select(:course_id, options_for_select(Course.all.map {|c| [c.name, c.id]},), class: 'form-control') %>
        </div>

        <div class="form-group">
          <%= f.label :document_url %>
          <%= f.text_field :document_url, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :video_url %>
          <%= f.text_field :video_url, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Create', class: 'btn btn-primary pull-right' %>
        </div>
      </div>

  <% end %>
</div>

app/views/admin/lessons/index.html.erb
<div class="container">
  <h2>
    <div class="pull-left">Lessons</div>
    <div class="pull-right">
      <%= link_to 'New lesson', new_admin_lesson_path %>
    </div>

  </h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Course</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @lessons.each do |lesson| %>
        <tr>
          <td><%= lesson.name %></td>

          <td>
            <%= lesson.course.name %>
          </td>

          <td>
            <%= link_to "View", '#' %>
            <%= link_to "Edit", "#" %>
            <%= link_to "Delete", "#" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/lessons/new.html.erb
<h1> New Lesson </h1>
<%= render 'form' %>

app/views/courses/_course.html.erb
<div class="col-sm-4" id="course-item-<%= course.id %>">
  <div class="course-item">
    <div class="card weater">
      <div class="city-selected">
        <div class="overlay"></div>
        <article>

          <div class="info">
            <div class="city"><%= course.name %></div>

            <div class="wind">
                <span>12 buổi</span>
            </div>
          </div>
        </article>

        <div class="btn btn-enrollment btn-success" data-id="<%= course.id %>">Enroll</div>

      </div>

      <div class="days">
        <div class="row row-no-gutter">
          <div class="col-md-4">
            <div class="day">
              <h4><strong>50</strong></h4>
              <h1>Students</h1>
            </div>
          </div>

          <div class="col-md-4">
            <div class="day">
              <h4><strong>50</strong></h4>
              <h1>Reviews</h1>
            </div>
          </div>

          <div class="col-md-4">
            <div class="day">
              <h4><strong>50</strong></h4>
              <h1>Likes</h1>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/dashboard.html.erb
<%#= @enrolled_courses.count %>

<% @enrolled_courses.each do |course| %>

    <div class="row">
      <div class="col-md-3">
        <%= image_tag course.image, width: '100%', class: 'img img-responsive' %>
      </div>

      <div class="col-md-9">
        <h2> <%= course.name %> </h2>
        <p> <%= course.description %> </p>
        <%= link_to "Go to course", my_course_path(course.id) %>
      </div>
    </div>
    <br>
<% end %>

app/views/courses/enroll.js.erb
$('#course-item-' + <%= @course.id %>).fadeOut(300);

app/views/courses/index.html.erb
<h3 style="margin-bottom: 50px;">
  <div class="container">
    <div class="row">
      <h3 style="padding-left: 15px; color: #333"> <%= t('.title') %> </h3>
      <% @courses.each do |_course| %>
          <%= render partial: "course", locals: { course: _course } %>
      <% end %>
    </div>
  </div>

  <%= #render partial: "course", collection: @feature_courses
  %>
</h3>

app/views/courses/show.html.erb
<%= render partial: 'shared/course_sidebar',
           locals: {course: @course, lessons: @lessons} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user && @current_user.admin? %>
      <%= render 'shared/sidebar' %>
    <% end %>

    <div class="container <%= @current_user ? 'active-user' : '' %>">
      <%= render '/shared/header' %>

      <div style="margin-top: 53px">
        <%= yield %>
      </div>
    </div>

    <%= render '/shared/footer' %>
  </body>
</html>

app/views/lessons/show.html.erb
<%= render partial: 'shared/course_sidebar',
           locals: {course: @course, lessons: @course.lessons} %>

<%= @lesson.id %>

app/views/shared/_course_sidebar.html.erb
<!-- Sidebar -->
<!-- Sidebar -->
<div id="sidebar-wrapper" style="top: 0px">
  <div class="list-group">

    <a class="list-group-item">
      <%= course.name %>
      <span id="menu-toggle" class="glyphicon glyphicon-align-justify"></span>
    </a>

    <% lessons.each do |lesson| %>
        <%= link_to lesson_path(course_id: course.id, id: lesson.id),
                    class: 'list-group-item' do %>
            <%= lesson.name %>
        <% end %>
    <% end %>

  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="social-icon animate pull-right">
      <li id="footer-fb-icon"><a href="#" title="facebook" target="_blank"><i class="fa fa-facebook"></i></a></li> <!-- change the link to social page and edit title-->
      <li id="footer-twitter-icon"><a href="#" title="twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
      <li id="footer-google-plus-icon"><a href="#" title="google plus" target="_blank"><i class="fa fa-google-plus"></i></a></li>
    </ul>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Home", root_path %>
        </li>

        <li><a href="#">About</a></li>
      </ul>

      <!--<form class="navbar-form navbar-left" role="search">-->
      <%= form_tag courses_search_path, class: 'navbar-form navbar-left', id: 'form-course-search' do %>
        <div class="form-group">
          <input type="text" name="query" id="course_search" class="form-control"
                 placeholder="Enter course name" style="width: 300px;">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      <% end %>

      <% if @current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li class="switch-language">
              <%= render 'shared/switch_language' %>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <b><%= @current_user.username %></b> <span class="caret"></span></a>

              <ul id="login-dp" class="dropdown-menu small">
                  <div class="row">
                    <div class="col-md-9 col-md-offset-1">
                      <li class="navright-item"><%= link_to 'Dashboard', dashboard_path %></li>
                      <li class="navright-item"><%= link_to 'Profile', "#" %></li>
                      <li class="navright-item"><%= link_to 'Logout', sessions_logout_path, method: :delete, class: 'text-danger' %></li>
                      <br />
                    </div>
                  </div>
              </ul>
            </li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">
                <%= render 'shared/switch_language' %>
              </p>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
              <ul id="login-dp" class="dropdown-menu">
                <li>
                  <div class="row">
                    <div class="col-md-12">
                      Login via
                      <div class="social-buttons">
                        <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                        <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                      </div>
                      or

                      <%= form_tag({controller: 'sessions', action: 'create'}, method: :post, class: 'form') do %>
                          <div class="form-group">
                            <label class="sr-only" for="exampleInputEmail2">Email address</label>
                            <%= text_field_tag :username_or_email, nil, class: 'form-control', placeholder: 'Email address' %>
                          </div>

                          <div class="form-group">
                            <label class="sr-only" for="exampleInputPassword2">Password</label>
                            <%= password_field_tag :password, nil, class: 'form-control', placeholder: 'Password' %>
                          </div>

                          <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                          </div>
                      <% end %>
                    </div>

                    <div class="bottom text-center">
                      New here ? <%= link_to raw("<b>Join Us</b>"), new_user_path %>
                    </div>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <div class="list-group">
    <a class="list-group-item">
      First item <span id="menu-toggle" class="glyphicon glyphicon-align-justify"></span>
    </a>
    <a href="/admin/courses" class="list-group-item">Course</a>
    <a href="/admin/lessons" class="list-group-item">Lessons</a>
  </div>
</div>

app/views/shared/_switch_language.html.erb
<%= link_to "En", root_path(locale: 'en') %> |
<%= link_to "Ge", root_path(locale: 'de') %>

app/views/users/new.html.erb
<div class="sign-form">
  <h1> Sign Up </h1>

  <% if @user.errors.any? %>
      <ul class="">
        <% for message_error in @user.errors.full_messages %>
            <li class="text-danger"><%= message_error %></li>
        <% end %>
      </ul>
  <% end %>

  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control' %>

    </br>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>


    </br>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    </br>
    <%= f.submit "Save", class: 'btn btn-primary', style: "min-width: 150px; float: right" %>
  <% end %>

  <div style="margin-top: 60px; text-align: right;">
    Already have an account?
    <b><%= link_to "Login now", login_path %></b>
  </div>
</div>	